name: Build and Release Ignition File
on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Create Ignition File
        uses: docker://quay.io/coreos/butane:release
        with:
          args: ucore-autorebase.butane -d ./ -o config.ign
      - name: Automatically increment tag
        id: tag_step
        uses: phish108/autotag-action@v1.1.55
        with:
          github-token: ${{ secrets.GITHUB_TOKEN}}
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          files: config.ign
          tag_name: ${{ steps.tag_step.outputs.new-tag }}
          target_commitish: ${{ github.sha }}
          previous_tag: ${{ steps.tag_step.outputs.tag }}
          generate_release_notes: true
